apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibm222
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flasknode
  template:
    metadata:
      labels:
        app: flasknode
    spec:
      containers:
        - name: ibmlast
          image: au.icr.io/myibm/mai_img
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
